### ISSUE TITLE
react版本和context语法

### ISSUE THREAD

**Issue by Vibing** [QianmiOpen/plume2#28]
大师你好~ 
我是陈龙 哈哈 忍不住来向你请教

目前`plume2`主要是基于`context api`，`context api`最大的方便之处是可以不用`props`透传，来解决数据变化后组件更新的问题。

`react 15.x`版本时官方不建议使用，到16版本后`context`语法变化也挺大（所以对于我而言`context`是个不稳定的存在）

大师有没有考虑过不使用`context`而用其他方式，比如`Object.defineProperties`或`Proxy`

**Comment by hufeng** [comment]
Object.defineProperties 也有不爽的地方
Proxy，保证不了浏览器的兼容性，而且不能polyfill
大势所趋是使用React16的context语法 关键是社区的库也需要follow

**Comment by hufeng** [comment]
会针对React新版本的context api做调整
